version: "2"

services:
  dictionary-app:
    image: dictionary-app
    container_name: dictionary-app
    restart: unless-stopped
    labels:
      - "traefik.http.services.dictionary-app.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.dictionary-app.rule=Host(`dictionary.galitianu.com`)"
      - "traefik.http.routers.dictionary-app.entrypoints=websecure"
      - "traefik.http.routers.dictionary-app.tls.certresolver=myresolver"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true